#!/usr/bin/env bash


logerr() { echo "$@" 1>&2; }
# FIXME this is bad pattern
(  uname | grep Darwin >/dev/null ) && open_command='open'
(  uname | grep Linux >/dev/null ) && open_command=xdg-open

if [[ -z "$open_command" ]] ; then
  logerr 'No command to open the url in the browser!'
fi


# TODO use getops
if [[ "$1" == '-h' ]] ; then
  echo 'git browse  to open current branch on GitHub'
  echo 'git browse <file>
  - to open file on current branch on GitHub'
  echo 'git browse <file> <line start><line end>
  - to open file on current branch on GitHub and to point to a
    given line or range of lines'
  echo 'git browse -c <commit sha> - open given commit on github'
  echo 'Example:'
  echo '    git browse bins/git-browse 5 10
                - will open https://github.com/lukaszkorecki/dotfiles/tree/master/bins/git-browse#L5-L10'
  echo '    git browse -c $(git log --pretty=oneline | grep fix | cut -f 1 -d ' ' | head -1)
                - opens latest commit with 'fix' in commit message'
  exit 0
fi


currentBranch() {
  git symbolic-ref HEAD | rev | cut -d/ -f 1 | rev
}

getRepoRoot() {
  # git rev-parse --show-toplevel
  if [[ -z "$1" || "$1" == "." ]] ; then
    echo ""
  else
    git ls-tree $(currentBranch) --full-name $1 | awk '{ print $4 }'
  fi
}

gitHubRepoUrl() {
  user_and_repo_name=$(git remote -v | grep origin | head -1 | cut -f2 -d:  |cut -d' ' -f 1 | sed 's/\.git.*//')
  echo "https://github.com/$user_and_repo_name/tree/$(currentBranch)"
}

# commit mode
# TODO use getops
if [[ "$1" == "-c" && "$2" != "" ]] ; then

  url=$(gitHubRepoUrl | sed "s/\/$(currentBranch)//" | sed "s/tree/commit/")/$2

else
  # detect if we passed line range
  if [[ "$2" != "" ]] ; then
    l1="L$2"
  fi

  if [[ "$3" != "" ]]; then
    l2="-L$3"
  fi

  path=$(getRepoRoot "$1")
  url="$(gitHubRepoUrl)/$path#$l1$l2"

fi

echo $url
eval "$open_command '$url'"
