#!/usr/bin/env bash

# utility / setup functions
logerr() { echo "$@" 1>&2; }

# detect open-url command
(  uname | grep Darwin >/dev/null ) && open_command='open'
(  uname | grep Linux >/dev/null ) && open_command='xdg-open'

if [[ -z "$open_command" ]] ; then
  logerr 'No command to open the url in the browser!'
fi

REMOTE=origin
SHOWHELP=n
SHOWCOMMIT=n
RANGE=""

while getopts "hc:R:r::" OPTIONS; do
  case "$OPTIONS" in
    h)
      SHOWHELP=y
      ;;

    c)
      SHOWCOMMIT=n
      COMMIT="$OPTARG"
      ;;

    R)
      REMOTE="$OPTARG"
      ;;

    r)
      RANGE="$OPTARG"
      ;;
  esac
done

# last unparsed arg becomes the file
FILE=$(echo "$*" | awk '{ print $NF }')

# TODO use getops and change this into a HEREDOC
if [[ $SHOWHELP == 'y' ]] ; then
  echo "TODO"
  exit 0
fi


# get current branch for given repo
currentBranch() {
  git symbolic-ref HEAD | rev | cut -d/ -f 1 | rev
}

# parse out a path to a file and/or repo
# first arg is the path to the file, falls back to repo root
getRepoRoot() {
  # git rev-parse --show-toplevel
  if [[ -z "$1" || "$1" == "." ]] ; then
    echo ""
  else
    git ls-tree $(currentBranch) --full-name $1 | awk '{ print $4 }'
  fi
}


# FIXME needs to handle more
# first arg is the remote name, falls back to 'origin'
# Example:
#   git@github.com:lukaszkorecki/git-browse.git (fetch)
#   ->
#   lukaszkorecki/git-browse
gitRepoUrl() {
  user_and_repo_name=$(git remote -v | grep -m1 $1 |  awk '{ print $2 }' | sed 's/git.*com.//' | sed 's/\.git//')
  if [[ -z $user_and_repo_name ]] ; then
    logerr "Remote named '$1' was not found!"
    exit 1
  fi

  echo "https://github.com/$user_and_repo_name/tree/$(currentBranch)"
}

# FIXME github only
getCommitUrl() {
  $(gitRepoUrl $REMOTE | sed "s/\/$(currentBranch)//" | sed "s/tree/commit/")/$2
}


parseRange() {
  if [[ -z "$1" ]] ; then
    echo ""
  else
    echo "#L$(echo "$1" | sed 's/\,/-L/')"
  fi
}
# commit mode
if [[ $SHOWCOMMIT == 'y' ]] ; then
  url=$(getCommitUrl $COMMIT)
else
  range=$(parseRange $RANGE)
  path=$(getRepoRoot $FILE)
  url="$(gitRepoUrl $REMOTE)/$path$range"

fi

echo $url
if [[ -z $DEBUG ]] ; then
  eval "$open_command '$url'"
fi
